###########
# Imports #
###########

import cv2

#############
# Constants #
#############

# <-- FEATURE EXTRACTOR --> #
DEFAULT_FEATURE_EXTRACTOR = cv2.xfeatures2d.SURF_create(extended=True)

# <-- MATCHER --> #
DEFAULT_MATCHER_INDEX_PARAMS = {'M': 15, 'indexThreadQty': 8, 'efConstruction': 100, 'post': 0}
DEFAULT_MATCHER_QUERY_PARAMS = {'efSearch': 100}

# <-- CLASSIFIERS --> #
DEFAULT_CLASSIFIER_IMAGE_SIZE = 256
DEFAULT_CLASSIFIER_KEYPOINT_STRIDE = 8
DEFAULT_CLASSIFIER_KEYPOINT_SIZES = [12, 24, 32, 48, 56, 64]

# <-- CLASSIFIER CUSTOM --> #
DEFAULT_CLASSIFIER_CUSTOM_MATCHER_PATH = "./files/matcher-classifier-custom.hnsw"
DEFAULT_CLASSIFIER_CUSTOM_K_NN = 1
DEFAULT_CLASSIFIER_CUSTOM_SCORE_SIGMA = 0.2
DEFAULT_CLASSIFIER_CUSTOM_FORCE_MATCHER_COMPUTE = False

# <-- CLASSIFIER BOW --> #
DEFAULT_CLASSIFIER_BOW_IMAGE_SIZE = 256
DEFAULT_CLASSIFIER_BOW_VOCAB_SIZE = 2000
DEFAULT_CLASSIFIER_BOW_VOCAB_PATH =  "./files/vocab.pkl"
DEFAULT_CLASSIFIER_BOW_CATALOG_FEATURES_PATH = "./files/catalog-features.pkl"
DEFAULT_CLASSIFIER_BOW_FORCE_VOCAB_COMPUTE = False
DEFAULT_CLASSIFIER_BOW_FORCE_CATALOG_FEATURES_COMPUTE = False

# <-- CLASSIFIER DEEP --> #
DEFAULT_CLASSIFIER_DEEP_MATCHER_PATH = "./files/matcher-classifier-deep.hnsw"
DEFAULT_CLASSIFIER_DEEP_FORCE_MATCHER_COMPUTE = False
DEFAULT_CLASSIFIER_DEEP_K_NN = 10
DEFAULT_CLASSIFIER_DEEP_SCORE_SIGMA = 0.2
DEFAULT_CLASSIFIER_DEEP_TRIPLET_MARGIN = 5.0
DEFAULT_CLASSIFIER_DEEP_TRAIN_EPOCHS = 1000
DEFAULT_CLASSIFIER_DEEP_TRAIN_BATCH_SIZE = 5
DEFAULT_CLASSIFIER_DEEP_TRAIN_AUGMENT_FACTOR = 3
DEFAULT_CLASSIFIER_DEEP_MODEL_PATH = "./files/triplet-model.hdf5"
DEFAULT_CLASSIFIER_DEEP_FORCE_TRAIN = False

# <-- DETECTOR --> #
DEFAULT_DETECTOR_CATALOG_IMAGE_WIDTHS = [800, 700, 600, 500, 400, 300, 200, 100]
DEFAULT_DETECTOR_QUERY_IMAGE_WIDTH = 4000
DEFAULT_DETECTOR_CATALOG_KEYPOINT_STRIDE = 8
DEFAULT_DETECTOR_QUERY_KEYPOINT_STRIDE = 4
DEFAULT_DETECTOR_KEYPOINT_SIZES = [24]
DEFAULT_DETECTOR_MATCHER_PATH = "./files/matcher-detector.hnsw"
DEFAULT_DETECTOR_FORCE_MATCHER_COMPUTE = False
DEFAULT_DETECTOR_BBOX_THRESHOLD = 200.
DEFAULT_DETECTOR_K_NN = 1
DEFAULT_DETECTOR_SCORE_SIGMA = 0.2

# <-- OTHER --> #
CATALOG_IMAGES_PATH = "../Images/Catalog"
CLASSIFICATION_QUERY_IMAGES_PATH = "../Images/Query"
CLASSIFICATION_GROUND_TRUTH_PATH = "../Images/ground_truth_classification.json"
DETECTOR_QUERY_IMAGES_PATH = "../Images/Query Raw/JPEGImages"
BACKGROUND_LABEL = "Background"
VERBOSE = True
COLORS = [(255, 255, 255), (128, 128, 128), (128,   0, 128),
          (  0,   0, 255), (  0, 255, 165), (  0, 255, 255),
          (133, 199,  21), (211, 148,   0), (154,   0, 250),
          (250, 135, 206), (158, 205, 183)]